In [3]:
import pandas as pd

In [7]:

df = pd.read_csv("olist_orders_dataset(1).csv")

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-10-2017 10:56,02-10-2017 11:07,04-10-2017 19:55,10-10-2017 21:25,18-10-2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24-07-2018 20:41,26-07-2018 03:24,26-07-2018 14:31,07-08-2018 15:27,13-08-2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08-08-2018 08:38,08-08-2018 08:55,08-08-2018 13:50,17-08-2018 18:06,04-09-2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18-11-2017 19:28,18-11-2017 19:45,22-11-2017 13:39,02-12-2017 00:28,15-12-2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13-02-2018 21:18,13-02-2018 22:20,14-02-2018 19:46,16-02-2018 18:17,26-02-2018 00:00

In [9]:
df.shape

(65535, 8)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       65535 non-null  object
 1   customer_id                    65535 non-null  object
 2   order_status                   65535 non-null  object
 3   order_purchase_timestamp       65535 non-null  object
 4   order_approved_at              65424 non-null  object
 5   order_delivered_carrier_date   64367 non-null  object
 6   order_delivered_customer_date  63581 non-null  object
 7   order_estimated_delivery_date  65535 non-null  object
dtypes: object(8)
memory usage: 4.0+ MB

In [13]:
df.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,65535,65535,65535,65535,65424,64367,63581,65535
unique,65535,65535,8,60693,38655,45749,53845,451
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-08-2018 12:05,10-01-2018 10:32,09-05-2018 15:48,21-05-2018 19:28,29-05-2018 00:00
freq,1,1,63580,22,73,28,7,367

In [15]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 111
order_delivered_carrier_date     1168
order_delivered_customer_date    1954
order_estimated_delivery_date       0
dtype: int64

In [17]:
df.duplicated().sum()

0

In [19]:
df.nunique()

order_id                         65535
customer_id                      65535
order_status                         8
order_purchase_timestamp         60693
order_approved_at                38655
order_delivered_carrier_date     45749
order_delivered_customer_date    53845
order_estimated_delivery_date      451
dtype: int64

In [23]:
ef = pd.read_csv("olist_order_reviews_dataset.csv")

ef.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18-01-2018 00:00,18-01-2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10-03-2018 00:00,11-03-2018 03:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17-02-2018 00:00,18-02-2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21-04-2017 00:00,21-04-2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01-03-2018 00:00,02-03-2018 10:26

In [27]:
ef.shape

(65535, 7)

In [33]:
ef.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                65535 non-null  object
 1   order_id                 65535 non-null  object
 2   review_score             65535 non-null  int64
 3   review_comment_title     7756 non-null   object
 4   review_comment_message   27053 non-null  object
 5   review_creation_date     65535 non-null  object
 6   review_answer_timestamp  65535 non-null  object
dtypes: int64(1), object(6)
memory usage: 3.5+ MB

In [35]:
ef.describe()

       review_score
count  65535.000000
mean       4.087663
std        1.345719
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [39]:
ef.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       57779
review_comment_message     38482
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [41]:
ef.duplicated().sum()

0

In [43]:
ef.nunique()

review_id                  65192
order_id                   65310
review_score                   5
review_comment_title        3265
review_comment_message     24104
review_creation_date         627
review_answer_timestamp    60790
dtype: int64

In [47]:
nf = pd.read_csv("olist_order_items_dataset.csv")

nf.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,19-09-2017 09:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,03-05-2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,18-01-2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,15-08-2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13-02-2017 13:57,199.90,18.14

In [51]:
nf.shape

(65535, 7)

In [55]:
nf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             65535 non-null  object
 1   order_item_id        65535 non-null  int64
 2   product_id           65535 non-null  object
 3   seller_id            65535 non-null  object
 4   shipping_limit_date  65535 non-null  object
 5   price                65535 non-null  float64
 6   freight_value        65535 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 3.5+ MB

In [57]:
nf.describe()

       order_item_id         price  freight_value
count   65535.000000  65535.000000   65535.000000
mean        1.200107    120.551483      19.957771
std         0.715333    182.494169      15.579806
min         1.000000      0.850000       0.000000
25%         1.000000     39.900000      13.080000
50%         1.000000     74.900000      16.290000
75%         1.000000    134.900000      21.170000
max        21.000000   6735.000000     375.280000

In [59]:
nf.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [63]:
nf.duplicated().sum()

0

In [65]:
nf.nunique()

order_id               57373
order_item_id             21
product_id             23531
seller_id               2747
shipping_limit_date    37809
price                   4696
freight_value           5818
dtype: int64

In [67]:
mf=pd.read_csv("olist_geolocation_dataset.csv")
mf.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [69]:
mf.shape

(65535, 5)

In [71]:
mf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   geolocation_zip_code_prefix  65535 non-null  int64
 1   geolocation_lat              65535 non-null  float64
 2   geolocation_lng              65535 non-null  float64
 3   geolocation_city             65535 non-null  object
 4   geolocation_state            65535 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 2.5+ MB

In [73]:
mf.describe()

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 65535.000000     65535.000000     65535.000000
mean                   2458.271870       -23.530172       -46.611012
std                     847.575792         0.040473         0.058960
min                    1001.000000       -23.883184       -46.861371
25%                    1509.000000       -23.560784       -46.654941
50%                    2537.000000       -23.538851       -46.621508
75%                    3193.000000       -23.496754       -46.568421
max                    3759.000000       -23.216648       -46.387234

In [77]:
mf.duplicated().sum()

26124

In [79]:
mf.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [81]:
mf.nunique()

geolocation_zip_code_prefix     1526
geolocation_lat                35840
geolocation_lng                35871
geolocation_city                   4
geolocation_state                  2
dtype: int64

In [83]:
gf=pd.read_csv("olist_customers_dataset.csv")
gf.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [85]:
gf.shape

(65535, 5)

In [87]:
gf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               65535 non-null  object
 1   customer_unique_id        65535 non-null  object
 2   customer_zip_code_prefix  65535 non-null  int64
 3   customer_city             65535 non-null  object
 4   customer_state            65535 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.5+ MB

In [89]:
gf.describe()

       customer_zip_code_prefix
count              65535.000000
mean               35088.344350
std                29745.687505
min                 1003.000000
25%                11346.000000
50%                24420.000000
75%                58514.500000
max                99990.000000

In [91]:
gf.duplicated().sum()

0

In [95]:
gf.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [97]:
gf.nunique()

customer_id                 65535
customer_unique_id          64051
customer_zip_code_prefix    13631
customer_city                3613
customer_state                 27
dtype: int64

In [101]:
kf=pd.read_csv("olist_products_dataset.csv")
kf.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [103]:
kf.shape

(32951, 9)

In [105]:
kf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [107]:
kf.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [109]:
kf.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [111]:
kf.nunique()

product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

In [113]:
kf.duplicated().sum()

0